import type { JobTemplateCreateInput } from '@/shared/schemas/job-template'

export type StarterRecipeInput = Omit<
  JobTemplateCreateInput,
  'scope' | 'workspaceSlug' | 'variables' | 'maxAttempts' | 'overallDeadlineMs'
> &
  Partial<Pick<JobTemplateCreateInput, 'variables' | 'maxAttempts' | 'overallDeadlineMs'>>

export const STARTER_RECIPES: StarterRecipeInput[] = [
  {
    slug: 'daily-database-backup',
    name: 'Daily database backup',
    tag: 'backups',
    icon: 'database',
    description: 'Triggers a backup endpoint every day at 2 AM.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '0 2 * * *', triggerTimezone: 'America/Phoenix' },
    targetRef: 'backup_endpoint',
    bodyTemplate: '{ "kind": "backup", "at": "{{ now | iso_date }}" }',
    headersTemplate: '{}',
  },
  {
    slug: 'hourly-health-check',
    name: 'Hourly health check',
    tag: 'health-checks',
    icon: 'activity',
    description: 'Pings a health endpoint every hour and expects 2xx.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '0 * * * *', triggerTimezone: 'America/Phoenix' },
    targetRef: 'health_endpoint',
    bodyTemplate: '',
    headersTemplate: '{}',
  },
  {
    slug: 'weekly-cleanup',
    name: 'Weekly cleanup',
    tag: 'maintenance',
    icon: 'trash-2',
    description: 'Triggers a cleanup endpoint every Sunday at 3 AM.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '0 3 * * SUN', triggerTimezone: 'America/Phoenix' },
    targetRef: 'cleanup_endpoint',
    bodyTemplate: '{ "kind": "cleanup" }',
    headersTemplate: '{}',
  },
  {
    slug: 'end-of-day-report',
    name: 'End-of-day report',
    tag: 'reports',
    icon: 'file-text',
    description: 'Generates and delivers an EOD report weekdays at 5 PM.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '0 17 * * MON-FRI', triggerTimezone: 'America/Phoenix' },
    targetRef: 'reports_endpoint',
    bodyTemplate: '{ "kind": "eod_report", "date": "{{ now | iso_date }}" }',
    headersTemplate: '{}',
  },
  {
    slug: 'first-of-month-invoice',
    name: 'First-of-month invoice',
    tag: 'reports',
    icon: 'receipt',
    description: 'Generates monthly invoices on the first day of each month at 9 AM.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '0 9 1 * *', triggerTimezone: 'America/Phoenix' },
    targetRef: 'billing_endpoint',
    bodyTemplate: '{ "kind": "invoice_run", "at": "{{ now | iso_date }}" }',
    headersTemplate: '{}',
  },
  {
    slug: 'continuous-integration-check',
    name: 'Continuous integration check',
    tag: 'integrations',
    icon: 'git-branch',
    description: 'Polls a build status endpoint every 15 minutes.',
    triggerKind: 'cron',
    triggerConfig: { cronExpression: '*/15 * * * *', triggerTimezone: 'America/Phoenix' },
    targetRef: 'ci_endpoint',
    bodyTemplate: '',
    headersTemplate: '{}',
  },
  {
    slug: 'webhook-receiver',
    name: 'Webhook receiver',
    tag: 'integrations',
    icon: 'webhook',
    description: 'Receives external POSTs and forwards the payload to a Target.',
    triggerKind: 'webhook',
    triggerConfig: {},
    targetRef: 'webhook_target',
    bodyTemplate: '{{ webhook_body }}',
    headersTemplate: '{}',
  },
  {
    slug: 'slow-polling',
    name: 'Slow polling',
    tag: 'health-checks',
    icon: 'timer',
    description: 'Polls a slower endpoint every 5 minutes with an extended deadline.',
    triggerKind: 'interval',
    triggerConfig: { intervalSeconds: 300 },
    targetRef: 'slow_endpoint',
    bodyTemplate: '',
    headersTemplate: '{}',
    overallDeadlineMs: 300_000,
  },
]
